### ISSUE TITLE
Extraneous references

### ISSUE THREAD

**Issue by mietek** [CeON/CERMINE#13]
Cermine does not handle correctly reference sections that are followed by an appendix.

The text following the reference section is mistakenly recognised as additional references.

### Example

Tested with 1.8-SNAPSHOT.

**Input**
- [BrownPalsberg2015.pdf](https://github.com/CeON/CERMINE/files/102143/BrownPalsberg2015.pdf)
- [BrownPalsberg2016.pdf](https://github.com/CeON/CERMINE/files/102145/BrownPalsberg2016.pdf)

**Output**
- [BrownPalsberg2015.cermxml.txt](https://github.com/CeON/CERMINE/files/102144/BrownPalsberg2015.cermxml.txt)
- [BrownPalsberg2016.cermxml.txt](https://github.com/CeON/CERMINE/files/102146/BrownPalsberg2016.cermxml.txt)

**Comment by dtkaczyk** [comment]
@mietek Please see [my comment](https://github.com/CeON/CERMINE/issues/12#issuecomment-174954427) in issue #12, the same applies here.

**Comment by dtkaczyk** [comment]
Since I cannot fix this directly, I am closing this issue.
