### ISSUE TITLE
Feature request: OCR

### ISSUE THREAD

**Issue by mietek** [CeON/CERMINE#14]
Some PDFs contain text that has been generated using an unspecified OCR process. For such PDFs, the quality of Cermine output depends directly on the quality of the particular OCR process, which may be far from satisfactory.

It would be great if Cermine performed its own OCR, and attempted to process both the existing and the newly recognised text, in order to get the best result.

Performing OCR may also be the only way to solve #11.
### Examples

Tested with 1.8-SNAPSHOT.

**Input**
- [BrownPalsbergReviewCopy.pdf](https://github.com/CeON/CERMINE/files/102147/BrownPalsbergReviewCopy.pdf)

**Output**
- [BrownPalsbergReviewCopy.cermxml.txt](https://github.com/CeON/CERMINE/files/102149/BrownPalsbergReviewCopy.cermxml.txt)

**Comment by dtkaczyk** [comment]
@mietek Thanks for this suggestion! This feature has been on our TODO list for a long time. Unfortunately, due to very limited resources we cannot progress as fast as we would like to. In the meantime, any feedback from the community is extremely valuable for us, as it helps us assign priorities to tasks.

**Comment by mietek** [comment]
Thanks. Is this TODO list public?

**Comment by mietek** [comment]
I think it would be interesting to investigate the OCR of vector shapes, as opposed to the usual way of performing OCR.  I expect there to be many situations such as #11, in which the glyph data in the vector layer is available.  In such situations, rendering vector shapes to bitmaps in order to perform OCR would seem like a step backwards.

**Comment by bwakkie** [comment]
While I like the idea I wonder how good the end result would be. To my experience OCR is better done manually. I use bash scripts to separate documents that still do need ocr and then do them manually as too many errors will occur to be put later back in the cermine stream.
