### ISSUE TITLE
Documentation for the XML output

### ISSUE THREAD

**Issue by Phyks** [CeON/CERMINE#15]
Hi,

Is there a documentation somewhere about the structure of the XML output, especially the available tags and so on? I could not find any.

Thanks!

**Comment by dtkaczyk** [comment]
The output conforms to NLM JATS format (http://jats.nlm.nih.gov/archiving/tag-library/1.1/). In fact we use a subset of the tags, but the overall document structure is the same. Right now we don't have any documentation covering this, I'll try to provide a short description as soon as I find time.

**Comment by Phyks** [comment]
Thanks for this link, I think it will be sufficient for my use case. A link to it in the README might be very helpful for newcomers I think.

**Comment by dtkaczyk** [comment]
@Phyks Thanks for the suggestion, I just added this information to README.

**Comment by Phyks** [comment]
Thanks!
