### ISSUE TITLE
Multithreading problems using CRFBibReferenceParser.parse method

### ISSUE THREAD

**Issue by tihi002** [CeON/CERMINE#17]
The CRFBibReferenceParser.parse(String affiliation) method is not working correctly using multiply threads. I could not figure out what is the actual problem. Sometimes indexOutOfBounds, sometimes nullPointer exception is being thrown. When I use one thread this problem is not occur. I created a synchronized wrapper method for parse method, and this is the only way I could make it work. The actual problem is that I have a big bunch of affiliations to parse. It would be great if I could use the power of multiply threads.

**Comment by dtkaczyk** [comment]
Thanks for reporting this. Could you provide a minimal code example I could use to replicate the problems you are experiencing?

Please also clarify whether you are interested in parsing citations or affiliations. From the description it seems like you are using citation parsing class to parse affiliations.

**Comment by dtkaczyk** [comment]
Since there were no additional information, I am closing this issue for now. Please reopen if you wish to revisit this problem.
