### ISSUE TITLE
Affiliations: Improve the way of finding country in affiliation string

### ISSUE THREAD

**Issue by lukdumi** [CeON/CERMINE#21]
Reported by @mkobos:

Affiliations: Improve way of finding country in affiliation string (this might potentially impact 23% of all records - these are the records where the country name (and thus country code) is missing)

```
1.1 Easy improvement. Look for the name of the country in affiliation string (this might solve the problem in up to 23%*25%= 6% of all affiliation records).
1.2 More difficult improvement. Recognize the country based on a dictionary of well-known scientific organizations and a dictionary of US states and major cities in various countries (this might solve the problem in up to 23%*80% = 18% of all affiliation records).
```

Note that all numbers come from the first version of report "Analysis of affiliations extracted by IIS from XMLs and PDFs" available at https://issue.openaire.research-infrastructures.eu/issues/2010, namely: https://issue.openaire.research-infrastructures.eu/attachments/download/509/2016-04-17_21_46_analysis.html. All these numbers are very rough approximations of the real values.

**Comment by lukdumi** [comment]
Part of it (the recognition of US country based on US states) has already been done.

**Comment by dtkaczyk** [comment]
The country dictionary has been extended, and we also perform the US states lookup. As for other suggestions, it would involve substantially more work and we are not going to do this anytime soon.
