### ISSUE TITLE
Affiliations: Improve recognizing whether a given affiliation text is really an affiliation

### ISSUE THREAD

**Issue by lukdumi** [CeON/CERMINE#22]
Originally reported by @mkobos:

Affiliations: Improve recognizing whether given affiliation text is really an affiliation. This can be done using a simple rule that checks whether the text is not too short and not too long (this might impact up to 6% of all affiliation records - these are the records where the affiliation text does not really correspond to an affiliation).

Note that all numbers come from the first version of report "Analysis of affiliations extracted by IIS from XMLs and PDFs" available at https://issue.openaire.research-infrastructures.eu/issues/2010, namely: https://issue.openaire.research-infrastructures.eu/attachments/download/509/2016-04-17_21_46_analysis.html. All these numbers are very rough approximations of the real values.

**Comment by dtkaczyk** [comment]
Upper limit of affiliation length were introduced in https://github.com/CeON/CERMINE/commit/d510ad9544a22475042af131a2ff67f4f59935a1. Lower limit of 12 existed before.
