### ISSUE TITLE
Affiliations: Improve mapping country name to country code

### ISSUE THREAD

**Issue by lukdumi** [CeON/CERMINE#23]
Originally reported by @mkobos:

Affiliations: Improve mapping country name to country code. In huge majority of cases when the country code is missing while country name is not, the content of country name field contains a substring which is a name of a country. In these cases it should be possible to assign the correct country code. This problem appears in up to 1.6% of all affiliation records (since this is the percentage of records where country code is missing while country name is not).

Note that all numbers come from the first version of report "Analysis of affiliations extracted by IIS from XMLs and PDFs" available at https://issue.openaire.research-infrastructures.eu/issues/2010, namely: https://issue.openaire.research-infrastructures.eu/attachments/download/509/2016-04-17_21_46_analysis.html. All these numbers are very rough approximations of the real values.

**Comment by dtkaczyk** [comment]
Improved in commit https://github.com/CeON/CERMINE/commit/83133de0f62e0a968cb0cec55ce600d6172c09f8
