### ISSUE TITLE
Affiliations: Recognize that some texts currently provided by CERMINE as affiliations are certainly not affiliations

### ISSUE THREAD

**Issue by lukdumi** [CeON/CERMINE#24]
Originally reported by @mkobos:

Affiliations: Recognize that some texts currently provided by CERMINE as affiliations are certainly not affiliations, e.g.: "Electronic address:" (this is the most numerous "affiliation" - it can be found in 0.03% of all affiliation records), "These authors contributed equally to this work".

Note that all numbers come from the first version of report "Analysis of affiliations extracted by IIS from XMLs and PDFs" available at https://issue.openaire.research-infrastructures.eu/issues/2010, namely: https://issue.openaire.research-infrastructures.eu/attachments/download/509/2016-04-17_21_46_analysis.html. All these numbers are very rough approximations of the real values.

**Comment by dtkaczyk** [comment]
Improved in commit https://github.com/CeON/CERMINE/commit/274925262719cb9be4428f1d70b314fdd1064c3c
