### ISSUE TITLE
Affiliations: Improve cleaning the affiliation string 

### ISSUE THREAD

**Issue by lukdumi** [CeON/CERMINE#25]
Originally reported by @mkobos:

Affiliations: Improve cleaning the affiliation string because in a small number of cases, the organization field contains some text that doesn't belong there (e.g. address, short name, name of the organization in different language, unrelated text) This might impact up to 20% of all affiliation records.

Note that all numbers come from the first version of report "Analysis of affiliations extracted by IIS from XMLs and PDFs" available at https://issue.openaire.research-infrastructures.eu/issues/2010, namely: https://issue.openaire.research-infrastructures.eu/attachments/download/509/2016-04-17_21_46_analysis.html. All these numbers are very rough approximations of the real values.

**Comment by lukdumi** [comment]
It might already partially be done by "regexps stripping unwanted affiliation parts (related to emails and dates) extended to cover some new cases"

**Comment by dtkaczyk** [comment]
Improved in commit https://github.com/CeON/CERMINE/commit/274925262719cb9be4428f1d70b314fdd1064c3c
