### ISSUE TITLE
Can not access Webservice "http://cermine.ceon.pl/extract.do" 

### ISSUE THREAD

**Issue by JishaGeorge** [CeON/CERMINE#26]
Hello Support,

I tried to consume the above given rest service in .NET application. Do you have any .wsdl file to generate proxy in .Net?
Otherwise please guide me on how to extract pdf documents in .NET.
Do you have any .NET library to make use of this CERMINE functionalities? 

Thanks in advance,
Jisha

**Comment by dtkaczyk** [comment]
@JishaGeorge In this situation it is probably the best to download executable JAR from the repository and execute it from the application just as any command line program. You will find more information about using JAR file in the README.
