### ISSUE TITLE
article-meta elements are out of order and fail JATS validation

### ISSUE THREAD

**Issue by axfelix** [CeON/CERMINE#37]
As much as I hate having to conform to ordered XML schemas, I think this is technically a bug as it does fail validation and can cause some JATS apps to panic.

Right now, in CERMINE output, `<abstract/>` and `<kwd-group/>` come before `<pub-date/>` and other associated elements (`<volume/>`, etc), which causes an error (you can reproduce in testing with just `xmllint --valid`); these should be moved to the end of `<article-meta/>`.

**Comment by dtkaczyk** [comment]
@axfelix thanks for reporting. I fixed the element order and also other issues related to identifiers (the changes are in master). I was able to successfully validate the resulting files. If you still experience any errors, let me know.

**Comment by axfelix** [comment]
Thanks!
