### ISSUE TITLE
improve accuracy of doi extraction

### ISSUE THREAD

**Issue by antonkulaga** [CeON/CERMINE#39]
I use Cermine in my little console utility to extract references from papers. I noticed that there are often mistakes in doi extraction, the most common one - is adding extra bracket to the end (that is why I manually remove it in my code https://github.com/antonkulaga/extractor/blob/master/src/main/scala/org/comp/bio/aging/extractor/Reference.scala#L22 ). Please, improve doi extraction accuracy!

**Comment by dtkaczyk** [comment]
@antonkulaga Thanks for reporting this. Could you provide a few example references from your papers as test cases?

**Comment by antonkulaga** [comment]
[1-8-2017_Mammalian.pdf](https://github.com/CeON/CERMINE/files/745528/1-8-2017_Mammalian.pdf)
Here is the paper. You can run CERMINE on it and see that many doi-s are no recognized correctly

**Comment by dtkaczyk** [comment]
@antonkulaga Thanks. I commited the fix for this into the master. Please check whether this solves this issue.

**Comment by dtkaczyk** [comment]
@antonkulaga I am assuming the issue was solved. Please reopen if you still experience these problems.
