### ISSUE TITLE
Use enums for identifiers

### ISSUE THREAD

**Issue by tobiasdiez** [CeON/CERMINE#42]
I didn't know which values I can pass to [getId](https://github.com/CeON/CERMINE/blob/master/cermine-impl/src/main/java/pl/edu/icm/cermine/metadata/model/DocumentMetadata.java#L81) until I found the constants [ID_DOI, ID_URN, ...](https://github.com/CeON/CERMINE/blob/master/cermine-impl/src/main/java/pl/edu/icm/cermine/metadata/model/DocumentMetadata.java#L316).
In my opinion it would make the code a bit clearer if you use an enum for the possible identifier types.

A similar remark applies to the different [types of dates](https://github.com/CeON/CERMINE/blob/31f97041552b814d95838ef9c9c01e5223d113dc/cermine-impl/src/main/java/pl/edu/icm/cermine/metadata/model/DocumentDate.java#L57).

**Comment by dtkaczyk** [comment]
@tobiasdiez Thanks for the suggestion. Please take a look at [this branch](https://github.com/CeON/CERMINE/tree/enums_identifiers), especially [pl.edu.icm.cermine.metadata.model package](https://github.com/CeON/CERMINE/tree/enums_identifiers/cermine-impl/src/main/java/pl/edu/icm/cermine/metadata/model), where I refactored the code a little bit. Do you think this will be easier to use?

**Comment by tobiasdiez** [comment]
This code indeed looks easier to use and more readable to me. Thanks!

**Comment by dtkaczyk** [comment]
Great. It's merged into master and will be part of the next release.
