### ISSUE TITLE
.jar won't run

### ISSUE THREAD

**Issue by VineetChauhanQE** [CeON/CERMINE#46]
I have downloaded  "cermine-impl-1.9-jar-with-dependencies.jar" on window 10. 

Create a folder in C:\NewTest and placed it.

Location of jar is C:\NewTest\cermine-impl-1.9-jar-with-dependencies.jar

Placed the pdf under a folder like C:\NewTest\Input\

Navigate to command prompt and type below command

java -cp cermine-impl-1.9-jar-with-dependencies.jar pl.edu.icm.cermine.ContentExtractor -path C:\NewTest\Input\

Getting error "Error: Could not find or load main class pl.edu.icm.cermine.ContentExtractor"

**Comment by dtkaczyk** [comment]
@VineetChauhanQE Indeed, there seems to be some problem with version JAR 1.9 in our repository. I checked all newer versions (1.10, 1.11 and 1.12), and they all seem fine. Could you try using the newest CERMINE version?

**Comment by VineetChauhanQE** [comment]
I have checked with the latest one and its working fine. :) Thanks :)
