### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by dleeftink** [CeON/CERMINE#48]
I am obviously doing something wrong here, as trying to run the latest 1.9 with dependencies from the terminal keeps returning "Error: Could not find or load main class pl.edu.icm.cermine.ContentExtractor". Having re-installed Java and a reset jre/path home a couple of times, I wonder what I am missing. Running on Windows 10 x64 with Java 32-bit (131).

**Comment by dtkaczyk** [comment]
Hi @dleeftink !

The latest version is in fact 1.12, unfortunately the repository sorts the versions lexicographically and it's easy to miss the versions larger than 1.9. We are working on correcting this.

In the meantime, please use version 1.12, it should work.

**Comment by dleeftink** [comment]
I figured as much, thanks for the clarification! The 1.12 version is working great, are there any configuration files I can access?

**Comment by dtkaczyk** [comment]
You should be able to set some options through the command line arguments. The configuration file covers the models used and you shouldn't need your own unless you want to build your own classification models. What would you like to configure?

**Comment by dleeftink** [comment]
Thanks for the quick reply! At the moment, I do not want to build classification models but rather (re-)structure the output from batch processing a large corpus of PDF's. For a large scale topic modeling project, I would like to structure the output generated by Carmine in such a way that I can cross-reference bodies of text to headers, and headers to article titles, as well as using the keywords to assess the general degree of 'relatedness' between titles <> keywords <> headers <> sections. 

For this, I would only need [Article Title | Keywords | Abstract | Section Header | Body | Section Header | Body | etc] in a structured XML, as I can then point the topic modeling scripts/software to the relevant segments within documents. Before, I used LAPDFToText, which enables the user to provide 'rule-files' to markup the resulting output; however it is not as flexible for detecting various types of article markup as Carmine is.

Although I might be able to crunch the XML generated by Cermine after normal operating procedures, I would rather like to format the XML during batch processing to minimize overhead. Would this be possible by adjusting the configuration file?

**Comment by dtkaczyk** [comment]
I'm afraid not, you can either parse the resulting XML or write you custom extractor using CERMINE's code.

**Comment by dleeftink** [comment]
Ok, thanks for clearing things up! And thanks for this incredible piece of software!
