### ISSUE TITLE
Cermine code extension

### ISSUE THREAD

**Issue by naziarumana** [CeON/CERMINE#50]
I would like to extend the cermine code. I would like to add up new keywords for extraction.For eg. I tried removing "Prof." keyword from author enhancer and "Case Report" keyword from title enhancer. and gave the input pdf document and checked but it did not reflect in output xml file. Can anyone help me on this.

**Comment by dtkaczyk** [comment]
@naziarumana plase provide a PDF file or files you have problems with along with a list of issues you experienced. I will take a look.

**Comment by dtkaczyk** [comment]
I am closing this issue for now, if you want to come back to it please reopen.
