### ISSUE TITLE
Bibtext Export

### ISSUE THREAD

**Issue by stzellerhoff** [CeON/CERMINE#59]
Hi!

Using a current snapshot build, I was able to export references as a bibtex file, but the different authors were not correctly separated by "and" but with a comma:

`@article{Peiker2016,
        author = {Peiker, C, Pott, C, Eckardt, L, Kelm, M, Shin, DI, Willems, S},
        doi = {10.1093/europace/euv056},
        journal = {Europace},
        pages = {332--339},
        title = {Dual atrioventricular nodal non-re-entrant tachycardia},
        volume = {18},
        year = {2016},
}`

Furthermore, duplicate citekeys were generated.

Stephan

**Comment by dtkaczyk** [comment]
The first problem is related to the citation parser erroneously tagging metadata in the reference string. I plan to retrain it on a more diverse set in the near future, which might help in this case. In general, however, we cannot guarantee the extraction results are always 100% correct.

I might be able to correct the second issue. Could you please provide a PDF file that causes these errors?

**Comment by dtkaczyk** [comment]
@stzellerhoff I am closing this issue, please reopen if you wish to investigate this.
