### ISSUE TITLE
Keyword extraction

### ISSUE THREAD

**Issue by philonor** [CeON/CERMINE#63]
Are there any plans to include keyword extraction based on the typical **Keywords** sections of, e.g., journal articles?

![image](https://user-images.githubusercontent.com/5816039/32540671-adaef326-c46d-11e7-8ca2-df771f4cf84d.png)

**Comment by dtkaczyk** [comment]
Hi @philonor, in general the keywords directly specified in the document are extracted. If you didn't see it in the output for specific articles, it might be the result of insufficient training of the current models.

**Comment by philonor** [comment]
@dtkaczyk Thanks for your reply! Do you want me to provide you with some PDFs the extraction of keywords failed for?

**Comment by dtkaczyk** [comment]
Sure, I'll take a look. I cannot promise this will be corrected, though.

**Comment by dtkaczyk** [comment]
@philonor I am closing this issue, please reopen if you wish to investigate further.

**Comment by philonor** [comment]
@dtkaczyk Thanks for closing. Any mail address I can send them to?

**Comment by dtkaczyk** [comment]
@philonor please send it to dtkaczyk@gmail.com
