### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by maenu** [CeON/CERMINE#70]
The recent commit 7686f97bb7d974a1d60ea77fdef042c2e47fb0c9 introduces a file `cermine-impl/src/main/java/pl/edu/icm/cermine/BibReferenceParser.java` declaring the class `CRFBibReferenceParser`, so class name and file name do not match. `CRFBibReferenceParser` also exists in the bibref package. This leads to duplicate classes and Javac refuses to compile with `mvn compile`:

```
[ERROR] bootstrap class path not set in conjunction with -source 1.6
/Users/maenu/Documents/phd/projects/LiteratureResearcher/pharo-6.1/pharo-local/iceberg/maenu/LiteratureResearcher/build/CERMINE/cermine-impl/src/main/java/pl/edu/icm/cermine/BibReferenceParser.java:[55,7] error: class CRFBibReferenceParser is public, should be declared in a file named CRFBibReferenceParser.java
```

**Comment by dtkaczyk** [comment]
@maenu thanks for spotting this! This file was committed by accident. I removed it, and the project should build now. Can you confirm this?
