### ISSUE TITLE
xref elements sometimes have multiple values for rid element

### ISSUE THREAD

**Issue by axfelix** [CeON/CERMINE#9]
Hi folks,

Looks like parsing this document with Cermine results in some weird rid= values for xref elements:

[doc2vec.pdf](https://github.com/CeON/CERMINE/files/92393/doc2vec.pdf)

`<xref ref-type="bibr" rid="16 14">(Mikolov et al., 2013c)</xref>`
`<xref ref-type="bibr" rid="25 27">(Socher et al., 2011b)</xref>`
`<xref ref-type="bibr" rid="17 16 20 13">(Morin &amp; Bengio, 2005; Mnih &amp; Hinton, 2008; Mikolov et al., 2013c)</xref>`
`<xref ref-type="bibr" rid="13 14 17">(Mikolov et al., 2013a)</xref>`
`<xref ref-type="bibr" rid="36">(Collobert &amp; Weston, 2008; Zhila et al., 2013)</xref>`

I'm pretty sure it's not valid JATS that way -- does it just break on (authorname, year) citation styles currently?

**Comment by dtkaczyk** [comment]
Hi axfelix,

as far as I know know, multiple rid values are allowed in JATS, see for example http://jats.nlm.nih.gov/archiving/tag-library/1.1/chapter/how-to-read.html:

> This kind of attribute must have a value that is the same as some ID value in the same document. IDREFs appear on elements (such as <xref>) that refer to other elements. IDREF attributes are generally named @rid. Some @rid attributes are of type IDREFS, which is simply a space-separated list of IDREF values.

This is especially useful for citations in the form of ranges (e. "[3-7]"). See also http://jats.nlm.nih.gov/archiving/tag-library/1.1/attribute/rid.html and this discussion: http://www.biglist.com/lists/lists.mulberrytech.com/jats-list/archives/201212/msg00001.html

A separate issue is that in your example rids are simple wrong (they point to wrong bibliography items). This is a problem with CERMINE's current matching code, it usually happens with (authorname, year) style, and especially when there are additional letters attached to years (2013c).

**Comment by axfelix** [comment]
Ah, good point! Sorry I didn't realize that. I think the usability point made by the listserv post remains -- at that point you have one anchor element that resolves to multiple targets in the bibliography -- but you're right that this is completely valid.
